document.writeln("    <div class=\'row bg-light mt-5\' style=\'\'>");
document.writeln("        <div class=\'col-12\'>");
document.writeln("            <br>");
document.writeln("        </div>");
document.writeln("        <div class=\'col-4\'>");
document.writeln("");
document.writeln("        </div>");
document.writeln("        <div class=\'col-4 bg-light text-center\' style=\'font-size: 12px;color: gray\'>");
document.writeln("            <p class=>地址：浙江省杭州市萧山区萧绍东路117号</p>");
document.writeln("            <p>邮箱：tedun@hztedun.com &nbsp&nbsp 联系电话：0571-82728276</p>");
document.writeln("            <p>版权所有：杭州特盾建筑材料有限公司</p>");
document.writeln("            <p><a href=\'https://beian.miit.gov.cn\' style=\'color: gray\'>许可证号：浙ICP备17012219号</a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'col-2\'>");
document.writeln("            &nbsp");
document.writeln("        </div>");
document.writeln("        <div class=\'col-1\'>");
document.writeln("            <div>");
document.writeln("                <p style=\'font-size: 12px\' class=\'badge badge-success\'>企业公众号</p>");
document.writeln("                <img src=\'/TEDUN/image/contect/QR_code_company.png\' alt=\'\' style=\'height: 100px;width: 100px;\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'col-1\'>");
document.writeln("            <div class=\' justify-content-center\' style=\'width: 100%\'>");
document.writeln("                <p style=\'font-size: 12px\' class=\'badge badge-primary\'>联系我们</p>");
document.writeln("                <img src=\'/TEDUN/image/contect/QR_code_GZ.png\' alt=\'\' style=\'height: 100px;width: 100px\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'col-1\'>");
document.writeln("            &nbsp");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <script src=\'/TEDUN/js/jquery-3.5.1.js\'></script>");
document.writeln("    <script src=\'/TEDUN/js/bootstrap.bundle.min.js\'></script>");
document.writeln("    <script src=\'/TEDUN/js/bootstrap.min.js\'></script>");
document.writeln("    <script src=\'/TEDUN/js/bootstrap.js\'></script>");