document.writeln("<!--nav start-->");
document.writeln("<nav class=\'navbar sticky-top navbar-expand-lg bg-light shadow\'>");
document.writeln("    <style>");
document.writeln("        .nav_text a{");
document.writeln("            font-size: 18px;");
document.writeln("            color: gray;");
document.writeln("            font-weight: bold;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("");
document.writeln("    <style>");
document.writeln("        .li_space li{");
document.writeln("            margin-left: 50px;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("    <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#nav_menu\' aria-controls=\'nav_menu\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("        <span class=\'navbar-toggler-icon\'></span>");
document.writeln("    </button>");
document.writeln("    <a href=\'/TEDUN/index.html\' class=\'navbar-brand ml-5\'><img src=\'\' alt=\'\'><img src=\'/TEDUN/image/logo/tedunlogo_small.png\' class=\'img\' alt=\'...\'></a>");
document.writeln("    <div class=\'collapse navbar-collapse w-100 li_space\' id=\'nav_menu\'>");
document.writeln("        <ul class=\'navbar-nav ml-5 nav_text\' >");
document.writeln("            <li class=\'nav-item py-3 px-3 d-none d-md-inline-block\'>");
document.writeln("                <a class=\'nav-link \' href=\'#\' >简介</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item dropdown py-3 px-3 d-none d-md-inline-block\' >");
document.writeln("                <a class=\'nav-link dropdown-toggle\' data-toggle=\'dropdown\' href=\'#\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>公司产品</a>");
document.writeln("                <div class=\'dropdown-menu\'>");
document.writeln("                    <a class=\'dropdown-item\' href=\'/TEDUN/product/trizip/index.html\'>直立锁边屋面系统</a>");
document.writeln("                    <a class=\'dropdown-item\' href=\'#\'>立边咬合屋面系统</a>");
document.writeln("                    <a class=\'dropdown-item\' href=\'#\'>平锁扣系列</a>");
document.writeln("                    <div class=\'dropdown-divider\'></div>");
document.writeln("                    <a class=\'dropdown-item\' href=\'#\'>配件</a>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item dropdown py-3 px-3  d-none d-md-inline-block\' >");
document.writeln("                <a class=\'nav-link dropdown-toggle\' data-toggle=\'dropdown\' href=\'#\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>关于公司</a>");
document.writeln("                <div class=\'dropdown-menu\'>");
document.writeln("                    <a class=\'dropdown-item\' href=\'#\'>公司介绍</a>");
document.writeln("                    <a class=\'dropdown-item\' href=\'#\'>公司环境</a>");
document.writeln("                    <a class=\'dropdown-item\' href=\'#\'>业务介绍</a>");
document.writeln("                </div>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item py-3 px-3 d-none d-md-inline-block\' >");
document.writeln("                <a class=\'nav-link\' href=\'#\'>联系我们</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item py-3 px-3 d-none d-md-inline-block\' >");
document.writeln("                <a class=\'nav-link\' href=\'#\'>公司概况</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("");
document.writeln("    </div>");
document.writeln("    <a href=\'https://hztyt.en.alibaba.com/\' class=\'float-right mx-5\' ><img src=\'/TEDUN/image/logo/alibaba.png\' alt=\'\' height=\'21px\' width=\'85px\'></a>");
document.writeln("    <a href=\'https://hztedun.en.made-in-china.com/\' class=\'float-right mx-5\' ><img src=\'/TEDUN/image/logo/mdChina_logo.png\' alt=\'\' height=\'21px\' width=\'85px\'></a>");
document.writeln("</nav>");
document.writeln("<!--nav end-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script src=\'/TEDUN/js/jquery-3.5.1.js\'></script>");
document.writeln("<script src=\'/TEDUN/js/bootstrap.min.js\'></script>");